### ISSUE TITLE
Delimit tokens by hyphens as well as spaces.

### ISSUE THREAD

**Issue by CirkuitBreaker** [reiman2222/IR-Program1#1]
Tokens also need to be hyphen delimited as well as space delimited. Observe the following paragraph:

Sorrow came--a gentle sorrow--but not at all in the shape of any
disagreeable consciousness.--Miss Taylor married.  It was Miss
Taylor's loss which first brought grief.  It was on the wedding-day
of this beloved friend that Emma first sat in mournful thought
of any continuance.  The wedding over, and the bride-people gone,
her father and herself were left to dine together, with no prospect
of a third to cheer a long evening.  Her father composed himself
to sleep after dinner, as usual, and she had then only to sit
and think of what she had lost.

The current code causes _came--a_ to become one token: _camea_. The same goes for _consciousness.--Miss_. This becomes consciousnessmiss. This is unacceptable and we have to fix it.

**Comment by reiman2222** [comment]
fixed
